/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ProTable: typeof import('./src/components/ProTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchForm: typeof import('./src/components/SearchForm.vue')['default']
    SearchFormItem: typeof import('./src/components/SearchFormItem.vue')['default']
    SearchFormTriggerItem: typeof import('./src/components/SearchFormTriggerItem.vue')['default']
    TheMenu: typeof import('./src/components/TheMenu.vue')['default']
    TheTabBar: typeof import('./src/components/TheTabBar.vue')['default']
  }
}
